# Generated by Django 5.0.6 on 2024-06-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0005_alter_tercero_ciudad_alter_tercero_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tercero',
            name='nit',
        ),
    ]
