# Generated by Django 4.2.2 on 2023-06-20 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='oportunidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.oportunidad', verbose_name='Oportunidad'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='tipogestiones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.tipogestion', verbose_name='Tipo de gestión'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='etapas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.etapa', verbose_name='Etapa'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='tipooportunidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.tipooportunidad', verbose_name='Tipo de oportunidad'),
        ),
    ]
