# Generated by Django 4.2.2 on 2023-06-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_documento_oportunidades_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapa',
            options={'ordering': ['porcentaje', 'etapa'], 'verbose_name': 'Etapa', 'verbose_name_plural': 'Etapas'},
        ),
        migrations.AlterModelOptions(
            name='oportunidad',
            options={'ordering': ['terceros', 'oportunidad'], 'verbose_name': 'Oportunidad', 'verbose_name_plural': 'Oportunidades'},
        ),
        migrations.AlterModelOptions(
            name='tipooportunidad',
            options={'ordering': ['tipo_oportunidad'], 'verbose_name': 'Tipo de oportunidad', 'verbose_name_plural': 'Tipos de oportunidad'},
        ),
        migrations.RenameField(
            model_name='etapa',
            old_name='nombre',
            new_name='etapa',
        ),
        migrations.RenameField(
            model_name='oportunidad',
            old_name='nombre',
            new_name='oportunidad',
        ),
        migrations.RenameField(
            model_name='tipooportunidad',
            old_name='nombre',
            new_name='tipo_oportunidad',
        ),
    ]
