# Generated by Django 4.2.5 on 2023-09-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_tercero_tipo_tercero_terceros_nombre_d2429c_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='tipo',
            field=models.CharField(choices=[('CT', 'Contacto'), ('SP', 'Suspecto'), ('LD', 'Lead'), ('OP', 'Oportunidad'), ('PR', 'Prospecto'), ('CL', 'Cliente'), ('ER', 'Erosión')], default='CT', max_length=2),
        ),
    ]
