# Generated by Django 4.2.5 on 2023-10-14 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_pais_iso"),
        ("terceros", "0004_alter_tipotercero_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tercero",
            name="ciudad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tercero_ciudad",
                to="base.ciudad",
                verbose_name="Ciudad",
            ),
        ),
        migrations.AlterField(
            model_name="tercero",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("contacto", "Contacto"),
                    ("suspecto", "Suspecto"),
                    ("lead", "Lead"),
                    ("oportunidad", "Oportunidad"),
                    ("prospecto", "Prospecto"),
                    ("cliente", "Cliente"),
                    ("erosion", "Erosión"),
                ],
                default="contacto",
                max_length=12,
            ),
        ),
    ]
