# Generated by Django 4.2.5 on 2023-10-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_segmento_alter_actividad_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pais",
            name="iso",
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
