# Generated by Django 5.0.6 on 2024-06-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pais_iso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['pais'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
    ]
